/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { CreateKnowledgeChunk201Response } from "../models";
// @ts-ignore
import type { CreateKnowledgeChunkRequest } from "../models";
// @ts-ignore
import type { DeleteKnowledgeChunk200Response } from "../models";
// @ts-ignore
import type { GetAllKnowledgeChunks200Response } from "../models";
/**
 * KnowledgeChunksApi - axios parameter creator
 * @export
 */
export const KnowledgeChunksApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Create a new knowledge chunk Copy
     * @param {CreateKnowledgeChunkRequest} [createKnowledgeChunkRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createKnowledgeChunk: async (
      createKnowledgeChunkRequest?: CreateKnowledgeChunkRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/knowledge-chunks`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createKnowledgeChunkRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete A Knowledge Chunk
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteKnowledgeChunk: async (
      id: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("deleteKnowledgeChunk", "id", id);
      const localVarPath = `/knowledge-chunks/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get All Knowledge Chunks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllKnowledgeChunks: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/knowledge-chunks`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * KnowledgeChunksApi - functional programming interface
 * @export
 */
export const KnowledgeChunksApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    KnowledgeChunksApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Create a new knowledge chunk Copy
     * @param {CreateKnowledgeChunkRequest} [createKnowledgeChunkRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createKnowledgeChunk(
      createKnowledgeChunkRequest?: CreateKnowledgeChunkRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CreateKnowledgeChunk201Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createKnowledgeChunk(
          createKnowledgeChunkRequest,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["KnowledgeChunksApi.createKnowledgeChunk"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete A Knowledge Chunk
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteKnowledgeChunk(
      id: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<DeleteKnowledgeChunk200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteKnowledgeChunk(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["KnowledgeChunksApi.deleteKnowledgeChunk"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get All Knowledge Chunks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllKnowledgeChunks(
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<GetAllKnowledgeChunks200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAllKnowledgeChunks(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["KnowledgeChunksApi.getAllKnowledgeChunks"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * KnowledgeChunksApi - factory interface
 * @export
 */
export const KnowledgeChunksApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = KnowledgeChunksApiFp(configuration);
  return {
    /**
     *
     * @summary Create a new knowledge chunk Copy
     * @param {CreateKnowledgeChunkRequest} [createKnowledgeChunkRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createKnowledgeChunk(
      createKnowledgeChunkRequest?: CreateKnowledgeChunkRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CreateKnowledgeChunk201Response> {
      return localVarFp
        .createKnowledgeChunk(createKnowledgeChunkRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete A Knowledge Chunk
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteKnowledgeChunk(
      id: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<DeleteKnowledgeChunk200Response> {
      return localVarFp
        .deleteKnowledgeChunk(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get All Knowledge Chunks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllKnowledgeChunks(
      options?: RawAxiosRequestConfig
    ): AxiosPromise<GetAllKnowledgeChunks200Response> {
      return localVarFp
        .getAllKnowledgeChunks(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * KnowledgeChunksApi - object-oriented interface
 * @export
 * @class KnowledgeChunksApi
 * @extends {BaseAPI}
 */
export class KnowledgeChunksApi extends BaseAPI {
  /**
   *
   * @summary Create a new knowledge chunk Copy
   * @param {CreateKnowledgeChunkRequest} [createKnowledgeChunkRequest]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof KnowledgeChunksApi
   */
  public createKnowledgeChunk(
    createKnowledgeChunkRequest?: CreateKnowledgeChunkRequest,
    options?: RawAxiosRequestConfig
  ) {
    return KnowledgeChunksApiFp(this.configuration)
      .createKnowledgeChunk(createKnowledgeChunkRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete A Knowledge Chunk
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof KnowledgeChunksApi
   */
  public deleteKnowledgeChunk(id: string, options?: RawAxiosRequestConfig) {
    return KnowledgeChunksApiFp(this.configuration)
      .deleteKnowledgeChunk(id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get All Knowledge Chunks
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof KnowledgeChunksApi
   */
  public getAllKnowledgeChunks(options?: RawAxiosRequestConfig) {
    return KnowledgeChunksApiFp(this.configuration)
      .getAllKnowledgeChunks(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
