export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import ToastContainer from "@/components/Toasts/ToastContainer";
import ConfirmationModal from "@/components/ConfirmationModal";
import InitializeUser from "@/components/InitializeUser";

const roboto = localFont({
  src: "../public/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf",
  variable: "--font-roboto",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ToastContainer />
        <ConfirmationModal />
        <InitializeUser />
        <main className="flex-grow">
          <div className="bg-slate-100 min-h-[calc(100vh-128px)]">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
              <div className="flex gap-8">
                <Sidebar />
                <section className="flex-1">{children}</section>
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
