/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateKnowledgeChunk201ResponseData } from './create-knowledge-chunk201-response-data';

/**
 * 
 * @export
 * @interface CreateKnowledgeChunk201Response
 */
export interface CreateKnowledgeChunk201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeChunk201Response
     */
    'status': string;
    /**
     * 
     * @type {CreateKnowledgeChunk201ResponseData}
     * @memberof CreateKnowledgeChunk201Response
     */
    'data': CreateKnowledgeChunk201ResponseData;
}

