/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateKnowledgeChunk201ResponseDataDepartment } from './create-knowledge-chunk201-response-data-department';
// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

/**
 * 
 * @export
 * @interface CreateKnowledgeChunk201ResponseData
 */
export interface CreateKnowledgeChunk201ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeChunk201ResponseData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeChunk201ResponseData
     */
    'content': string;
    /**
     * 
     * @type {Null}
     * @memberof CreateKnowledgeChunk201ResponseData
     */
    'point': Null;
    /**
     * 
     * @type {CreateKnowledgeChunk201ResponseDataDepartment}
     * @memberof CreateKnowledgeChunk201ResponseData
     */
    'department': CreateKnowledgeChunk201ResponseDataDepartment;
}

