/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateKnowledgeChunk201ResponseDataDepartment
 */
export interface CreateKnowledgeChunk201ResponseDataDepartment {
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeChunk201ResponseDataDepartment
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeChunk201ResponseDataDepartment
     */
    'name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateKnowledgeChunk201ResponseDataDepartment
     */
    'questions': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateKnowledgeChunk201ResponseDataDepartment
     */
    'knowledgeChunks': Array<string>;
}

