/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeleteKnowledgeChunk200ResponseData } from './delete-knowledge-chunk200-response-data';

/**
 * 
 * @export
 * @interface DeleteKnowledgeChunk200Response
 */
export interface DeleteKnowledgeChunk200Response {
    /**
     * 
     * @type {string}
     * @memberof DeleteKnowledgeChunk200Response
     */
    'status': string;
    /**
     * 
     * @type {DeleteKnowledgeChunk200ResponseData}
     * @memberof DeleteKnowledgeChunk200Response
     */
    'data': DeleteKnowledgeChunk200ResponseData;
}

