/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetAllKnowledgeChunks200ResponseDataInner } from './get-all-knowledge-chunks200-response-data-inner';

/**
 * 
 * @export
 * @interface GetAllKnowledgeChunks200Response
 */
export interface GetAllKnowledgeChunks200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAllKnowledgeChunks200Response
     */
    'status': string;
    /**
     * 
     * @type {Array<GetAllKnowledgeChunks200ResponseDataInner>}
     * @memberof GetAllKnowledgeChunks200Response
     */
    'data': Array<GetAllKnowledgeChunks200ResponseDataInner>;
}

