/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetAllKnowledgeChunks200ResponseDataInnerDepartment } from './get-all-knowledge-chunks200-response-data-inner-department';
// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

/**
 * 
 * @export
 * @interface GetAllKnowledgeChunks200ResponseDataInner
 */
export interface GetAllKnowledgeChunks200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetAllKnowledgeChunks200ResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllKnowledgeChunks200ResponseDataInner
     */
    'content'?: string;
    /**
     * 
     * @type {Null}
     * @memberof GetAllKnowledgeChunks200ResponseDataInner
     */
    'point'?: Null;
    /**
     * 
     * @type {string}
     * @memberof GetAllKnowledgeChunks200ResponseDataInner
     */
    'pointId'?: string;
    /**
     * 
     * @type {GetAllKnowledgeChunks200ResponseDataInnerDepartment}
     * @memberof GetAllKnowledgeChunks200ResponseDataInner
     */
    'department'?: GetAllKnowledgeChunks200ResponseDataInnerDepartment;
}

